# Generated by Django 5.2.4 on 2025-08-19 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumebackend', '0002_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='payload',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='history',
            name='action_type',
            field=models.CharField(choices=[('analyzer', 'Resume Analyzer'), ('builder', 'Resume Builder'), ('draft', 'Resume Draft')], max_length=20),
        ),
    ]
